### ISSUE TITLE
Can't install scoped packages

### ISSUE THREAD

**Issue by sean-clayton** [fl4re/sinopia#25]
Here's what I run:

```sh
npm i @kadira/storybook
```

Here's what gets logged:

```sh
http  <-- 404, user: undefined, req: 'GET /@kadira%2fstorybook', error: no such package available
```

It looks like it's sanitizing the `/` ?

**Comment by sean-clayton** [comment]
I found out how to fix it! I edited my `config.yaml` to look like this:

```yaml
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
```

Namely, that last line where I proxy to the regular npmjs registry.
