### ISSUE TITLE
Setup sionpia2 to not proxy to npmjs

### ISSUE THREAD

**Issue by vchimev** [fl4re/sinopia#30]
Hi,

I need to setup sinopia2 to not proxy to *npmjs* for my package. I removed the `proxy: npmjs` entry, but it still returns versions from *npmjs* instead of my local sinopia2.
```
packages:
  'my-package':
    access: $all
    publish: $authenticated
```
Any ideas? CC: @davidgaya

Thanks,
Vasil
